services:
  security-server:
    build:
      context: ./security            # security 서버 Dockerfile이 위치한 경로
      dockerfile: Dockerfile         # Dockerfile명
    container_name: security-server  # 컨테이너명
    ports:
      - "8080:8080"                  # 호스트 8080 → 컨테이너 8080 매핑(호스트에서 접근 가능하도록 외부 공개)
    environment:                     # 런타임 환경변수 (호스트의 .env 파일로 주입)
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      JWT_SECRET_KEY: ${JWT_SECRET_KEY}
      AES_SECRET_KEY: ${AES_SECRET_KEY}
    deploy:
      resources:
        limits:
          cpus: "1.0"                # 컨테이너가 최대 몇 개의 CPU 코어를 사용할 수 있는지 제한
          memory: 1g                 # 컨테이너가 사용할 수 있는 메모리 최대 용량 제한

  exchange-server:
    build:
      context: ./exchange            # exchange 서버 Dockerfile이 위치한 경로
      dockerfile: Dockerfile         # Dockerfile명
    container_name: exchange-server  # 컨테이너명
    ports:
      - "8081:8081"                  # 호스트 8081 → 컨테이너 8081 공개
    environment:
      REDIS_HOST: redis-db       # 여기에 Redis 컨테이너 이름 명시

    deploy:
      resources:
        limits:
          cpus: "1.0"                # 컨테이너가 최대 몇 개의 CPU 코어를 사용할 수 있는지 제한
          memory: 1g                 # 컨테이너가 사용할 수 있는 메모리 최대 용량 제한

  redis:
    image: redis:7.4.5               # Redis 도커 컨테이너
    container_name: redis-db
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  mysql:                        # MySQL 도커 컨테이너
    image: mysql:8.4.6
    container_name: mysql
    ports:
      - "3300:3306"             # 3306 포트는 로컬 MySQL 프로세스가 사용하므로 3300 포트로 할당
    environment:
      MYSQL_DATABASE: security
      MYSQL_USER: roots
      MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - mysql_data:/var/lib/mysql

volumes:                        # 컨테이너가 종료되어도 저장소에 적재된 데이터를 보존하기 위해
  mysql_data:
    driver: local
  redis_data:
    driver: local