spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:${MYSQL_PORT}/${MYSQL_DB_NAME}
    username: ${MYSQL_USERNAME}
    password: ${MYSQL_PASSWORD}
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
  jackson:
    property-naming-strategy: SNAKE_CASE

server:
  port: 8080

exchange-server:




jwt:
  secret-key: ${JWT_SECRET_KEY:mySuperSecretKey1ADADASDASDADASDASDADASDASDASD23!}
  access-token-expired-at: ${ACCESS_TOKEN_EXPIRED_AT:5}
  refresh-token-expired-at: ${REFRESH_TOKEN_EXPIRED_AT:7}

#aes:
#  secret-key: ${AES_SECRET_KEY}